In [1]:
import numpy as np
from numpy.random import randint as ri

In [2]:
np.array([1,2,3])

array([1, 2, 3])

In [3]:
a = np.array([[1,2],[3,4],[5,6]])
a.dtype

dtype('int32')

In [4]:
# all data convert into float
np.array(a,dtype=float)

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [5]:
#mat =  matrix
np.array(np.mat('1 2 3; 4 5 6;7 8 9'),dtype=float)

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [6]:
a = [1,2]
np.array(a)

array([1, 2])

In [7]:
b = np.asarray(a)
b

array([1, 2])

# Data Type

In [8]:
type(b)

numpy.ndarray

In [9]:
b.size

2

# arrange and linspace

In [10]:
list(range(1,15))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]

In [11]:
list(range(2.5,10.5))#show error if use flot value

TypeError: 'float' object cannot be interpreted as an integer

In [ ]:
np.arange(2.5,10.5)

In [ ]:
np.arange(1,10,2)

In [12]:
# reverse direction
np.arange(10,0,-2)

array([10,  8,  6,  4,  2])

In [13]:
np.linspace(10,40,5)#(start,end,number of data i want)

array([10. , 17.5, 25. , 32.5, 40. ])

In [14]:
np.linspace(1,2,5,endpoint=False)

array([1. , 1.2, 1.4, 1.6, 1.8])

# Matrix creation

In [15]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [16]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
np.ones((5,5))#(row,columns)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
#if you want to add any number 

In [50]:
5*np.ones((5,5))

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [53]:
mat1 = np.eye(5)
mat1

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

array([1. , 1.2, 1.4, 1.6, 1.8])

In [62]:
x = np.arange(30).reshape(5,6)
x

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

# Random Number Genreate

# rand

In [91]:
np.random.rand(10,5)

array([[0.73043404, 0.72578032, 0.90927397, 0.35196729, 0.68763518],
       [0.50230057, 0.72959949, 0.55705136, 0.94848257, 0.89397129],
       [0.47955331, 0.77844777, 0.96672452, 0.03914205, 0.13434188],
       [0.2122997 , 0.51691813, 0.47137074, 0.91001536, 0.1092377 ],
       [0.41503097, 0.61188728, 0.01164264, 0.20612459, 0.15550971],
       [0.4673916 , 0.18298873, 0.28998958, 0.86993801, 0.56117977],
       [0.04967697, 0.32215203, 0.28019026, 0.09739247, 0.19447933],
       [0.66202725, 0.03871293, 0.79760043, 0.85757499, 0.88168455],
       [0.39471047, 0.09871249, 0.21562266, 0.88192139, 0.06984956],
       [0.48366261, 0.9257313 , 0.296147  , 0.00151047, 0.86658767]])

In [88]:
np.random.rand(1,5,3)

array([[[0.69118189, 0.78743312, 0.91854496],
        [0.82191346, 0.38354306, 0.22581857],
        [0.74086772, 0.97282848, 0.8147808 ],
        [0.72511304, 0.0910327 , 0.20515757],
        [0.62064542, 0.1330509 , 0.49513411]]])

# randn

In [89]:
np.random.randn(1,5)

array([[ 0.81334928,  1.10544487, -0.54100619,  0.43920128, -0.59014969]])

In [92]:
np.random.randn(5,3)#(row,columns)

array([[ 0.04502373, -0.6398136 , -1.41583647],
       [-0.82066017, -0.58583604,  0.41279782],
       [ 0.06527103, -1.75528181, -1.39539447],
       [ 1.19946035, -0.8534587 , -0.70709033],
       [ 0.29879176,  1.96877012, -1.2567001 ]])

In [74]:
OTP = np.random.randint(10000,99999)
OTP

44489

In [106]:
np.random.randint(10,99,(7,4))#(start,end,(row,column))

array([[65, 10, 31, 53],
       [48, 59, 61, 13],
       [29, 24, 34, 82],
       [52, 37, 26, 24],
       [85, 83, 54, 83],
       [73, 38, 96, 59],
       [66, 50, 63, 50]])

# !reshaping

In [107]:
from numpy.random import randint as ri

In [110]:
rn = ri(1,99,50)
rn

array([43, 16, 88, 52, 31, 53, 91, 83, 26,  1, 89, 93, 22, 84, 59, 64,  4,
       56, 90, 80, 44, 50, 85, 71, 56, 14, 64, 65, 69, 41, 38, 58, 44, 77,
       81, 81, 64, 68, 37, 26, 69, 49, 72, 53, 54, 47, 41, 53, 48, 70])

In [113]:
s = rn.reshape(10,5)
s

array([[43, 16, 88, 52, 31],
       [53, 91, 83, 26,  1],
       [89, 93, 22, 84, 59],
       [64,  4, 56, 90, 80],
       [44, 50, 85, 71, 56],
       [14, 64, 65, 69, 41],
       [38, 58, 44, 77, 81],
       [81, 64, 68, 37, 26],
       [69, 49, 72, 53, 54],
       [47, 41, 53, 48, 70]])

# Sorting

In [121]:
n = ri(1,20,10)
n

array([14, 18, 14, 10, 19, 18,  4, 17, 17,  5])

In [124]:
np.sort(n)

array([ 4,  5, 10, 14, 14, 17, 17, 18, 18, 19])

In [125]:
s = rn.reshape(10,5)
s

array([[43, 16, 88, 52, 31],
       [53, 91, 83, 26,  1],
       [89, 93, 22, 84, 59],
       [64,  4, 56, 90, 80],
       [44, 50, 85, 71, 56],
       [14, 64, 65, 69, 41],
       [38, 58, 44, 77, 81],
       [81, 64, 68, 37, 26],
       [69, 49, 72, 53, 54],
       [47, 41, 53, 48, 70]])

In [127]:
np.sort(s)#short to row 

array([[16, 31, 43, 52, 88],
       [ 1, 26, 53, 83, 91],
       [22, 59, 84, 89, 93],
       [ 4, 56, 64, 80, 90],
       [44, 50, 56, 71, 85],
       [14, 41, 64, 65, 69],
       [38, 44, 58, 77, 81],
       [26, 37, 64, 68, 81],
       [49, 53, 54, 69, 72],
       [41, 47, 48, 53, 70]])

In [ ]:
# if data short in columns

In [129]:
np.sort(s,axis=0)

array([[14,  4, 22, 26,  1],
       [38, 16, 44, 37, 26],
       [43, 41, 53, 48, 31],
       [44, 49, 56, 52, 41],
       [47, 50, 65, 53, 54],
       [53, 58, 68, 69, 56],
       [64, 64, 72, 71, 59],
       [69, 64, 83, 77, 70],
       [81, 91, 85, 84, 80],
       [89, 93, 88, 90, 81]])

In [132]:
np.sort(s,axis=0,kind='stable')

array([[14,  4, 22, 26,  1],
       [38, 16, 44, 37, 26],
       [43, 41, 53, 48, 31],
       [44, 49, 56, 52, 41],
       [47, 50, 65, 53, 54],
       [53, 58, 68, 69, 56],
       [64, 64, 72, 71, 59],
       [69, 64, 83, 77, 70],
       [81, 91, 85, 84, 80],
       [89, 93, 88, 90, 81]])

In [4]:
g = ri(1,10,5)
g

array([4, 9, 4, 5, 8])

In [5]:
g.min()

4

In [6]:
g.max()

9

In [18]:
p = ri(1,50,50).reshape(10,5)
p

array([[18, 29, 29, 34, 41],
       [46, 32, 49,  8, 29],
       [16, 35, 14, 47, 47],
       [30, 11, 33, 25, 25],
       [10, 38, 24, 15, 40],
       [ 6,  6, 17, 25, 46],
       [17,  8,  3,  5, 28],
       [ 4, 28, 25, 46, 37],
       [37, 26, 42, 22, 40],
       [48,  3,  3, 45, 43]])

In [20]:
p.max()

49

# next class 11sep

# row to columns

In [21]:
add_col = np.array([[0,1,2,3,4]])

In [22]:
add_col

array([[0, 1, 2, 3, 4]])

In [23]:
add_col.T #row to columns

array([[0],
       [1],
       [2],
       [3],
       [4]])

# add to array

In [27]:
y = np.zeros((3,3))
y

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [29]:
x = np.array([1,0,1])
x

array([1, 0, 1])

In [31]:
y+x

array([[1., 0., 1.],
       [1., 0., 1.],
       [1., 0., 1.]])

# Array Math

In [39]:
math1 = np.array(ri(1,10,9)).reshape(3,3)

math2 = np.array(ri(1,10,9)).reshape(3,3)
math1

array([[8, 5, 7],
       [4, 8, 2],
       [8, 3, 1]])

In [40]:
math2

array([[8, 1, 2],
       [4, 5, 7],
       [1, 2, 6]])

In [45]:
np.sqrt(math1)

array([[2.82842712, 2.23606798, 2.64575131],
       [2.        , 2.82842712, 1.41421356],
       [2.82842712, 1.73205081, 1.        ]])

In [47]:
np.log10(math1)

array([[0.90308999, 0.69897   , 0.84509804],
       [0.60205999, 0.90308999, 0.30103   ],
       [0.90308999, 0.47712125, 0.        ]])

In [51]:
np.log10(53)

1.724275869600789

In [53]:
np.exp(math1)

array([[2.98095799e+03, 1.48413159e+02, 1.09663316e+03],
       [5.45981500e+01, 2.98095799e+03, 7.38905610e+00],
       [2.98095799e+03, 2.00855369e+01, 2.71828183e+00]])